server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://47.94.94.87:3306/weibo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      filters: stat,wall,slf4j
    username: root
    password: root

  redis:
    host: 47.94.94.87
    password: root

  rabbitmq:
    host: 47.94.94.87
    port: 5672
    username: user
    password: 123456
    virtual-host: /weibo
    listener:
      direct:
        default-requeue-rejected: false
  mvc:
    format:
      date: yyyy-MM-dd

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.aynu.java2.weibo.entity